### PR TITLE
Add support for browsers integration by mimicking KeePassHttp plugin.

### PR DESCRIPTION
**Pull request by eugenesan**
Implementation based on work of
 * [typz](https://gitorious.org/keepassx/keepassx-http)
 * [jdachtera](https://github.com/jdachtera/keepassx)
 * [Ivan0xFF](https://github.com/Ivan0xFF/keepassx)
 * [denk-mal](https://github.com/denk-mal/keepassx)

### CODE REVIEW

**Comment by eugenesan** [comment]
Builds fail since Travis CI miss required libraries: LibMicroHTTPD and  QJSON.
Can someone add them?

**Comment by greenify** [comment]
Thanks so much for pushing this forward. 

Have a look at http://docs.travis-ci.com/user/installing-dependencies/ - you probably want to add sth like that 

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y qjson libmicrohttpd

**Comment by eugenesan** [comment]
Add qjson and libmicrohttpd to Travis.

**Comment by eugenesan** [comment]
Seems like Travis uses outdated Ubuntu and OSX environment has issues compiling with MicroHTTPD.
Any ideas?

**Comment by alerque** [comment]
Do you have a version of this git branch with the original commits of other people's code? Having it all squashed in with yours (a) doesn't credit them (b) makes the code really hard to review and see what happened when and why.

**Comment by eugenesan** [comment]
@alerque I totally agree with you, but there seems to be no "shared" history among original trees.
I could rebase upon work of two latest authors but that would be unfair to two first authors.

I believe crediting authors in comment and providing links to their trees is a good compromise.

**Comment by alerque** [comment]
@eugenesan This is what rebase and cherry-pick are for are for. This is not an either-or equation, you can do both. And separating that merging work from your own add on work later is very important to the code review process (which this project already has enough of a problem with upstream).

**Comment by debfx** [comment]
Without having looked at the code much yet:
The lack of copyright attribution (some files have none, some have my name?!), license information (have all the authors licensed the code at least as GPL-2 and GPL-3?) and commit history is definitely a blocker.

**Comment by eugenesan** [comment]
Add new PR  #111 with requested details.

**Pull request closed without merging**
