### PR TITLE
Add CSV Import Support (KeePassX and LastPass CSV supported)

### PR DESCRIPTION
**Pull request by gamaral**
With the LastPass mass exodus Today, I thought it helpful to have a way to import the from CSV they generate.

Tested it with both a LastPass CSV export and a KeePassX CSV export, both seem to work fine. :)

### CODE REVIEW

**Comment by labianchin** [comment]
+1

That would be very useful!

**Comment by gamaral** [comment]
Glad you think so. :)

I created an issue for it on the project Redmine: https://www.keepassx.org/dev/issues/369

Unfortunately this project seems to be a bit of a dark hole... so this feature may go no where fast.

**Comment by fourzerofour** [comment]
Hey @gamaral thanks for the effort. I built keepassx with your csv import patch earlier today and upon importing lastpass csv export file, I got "Column mismatch." error. Here's the column headers in the first line of the csv file if it can be helpful

`url,username,password,extra,name,grouping,fav`

**Comment by kofronpi** [comment]
So...any updates on this ? I want to move away from LastPass. thanks :)

**Comment by TheZ3ro** [comment]
@kofronpi check out [KeePassXC](https://github.com/keepassxreboot/keepassxc) https://keepassxc.org Seems that KeePassX is not maintained anymore

**Comment by kofronpi** [comment]
@TheZ3ro  thanks !

**Pull request closed without merging**
