### PR TITLE
NOTE: KeepassX is no longer maintained.  Use KeepassXC instead.

### PR DESCRIPTION
**Pull request by jonathancross**
Considering there has been no releases since September 2016, pull requests are not being discussed or merged and the project maintainer [stopped responding to bugs in October 2016](https://dev.keepassx.org/activity?from=2016-10-27&user_id=3), it seems this project is no longer being maintaned.

I would like to suggest that we update the README in theis PR and encourage development to move to **[KeepassXC](https://github.com/keepassxreboot/keepassxc)** which has a thriving dev community: https://keepassxc.org

### CODE REVIEW

**Comment by mnoack** [comment]
@BlueIce @debfx What do you think about this? I've been looking for password managers and I must say, the confusion of KeyPass vs KeyPassX vs KeyPassXC has been confusing.

My personal thoughts on this is are actually to give KeyPassXC keys to the kingdom so they can direct the website/github/etc. to KeyPassXC, and even pull the various packages from repos.

Thank You very much for your efforst though, it looks like an excellent platform which the KeyPassXC people are building on top of.

**Comment by jryberg** [comment]
I moved to KeePassXC and I'm happy about that decision.

Credit to the original team that brought KeePassX to life, with new energy I hope KeePassXC will be an active fork.

**Comment by mevsme** [comment]
due to impossibility to compile fucking source code of 0.4 let's try a new one.

**Comment by debfx** [comment]
I don't have much time to work on KeePassX right now.
However I'm still maintaining it so at least important bugs (especially security issues) will get fixed.

**Comment by brokensh3ll** [comment]
Imo, KeepassX doesn't require future features.It Simple, lightweight, secure. If you are looking for a fancy password manager, less secure, go for keepassxc

**Pull request closed without merging**
