### PR TITLE
Bug #283

### PR DESCRIPTION
**Pull request by pakdel**
Updated messages related to saving and closing a database to make them more clear about what is going to happen.

### CODE REVIEW

**Comment by debfx** [comment]
Looks good.

We could go even further by allowing to save the database while an entry is being edited.
So basically applying the current changes to the entry and saving the database.

**Comment by pakdel** [comment]
Yes, we could, but personally I prefer the current "decide on the task in hand before proceeding" approach.
Do you think what you mentioned is what majority of user want?

**Comment by p120ph37** [comment]
Either way, the user must be made to decide on the task in hand - it's just a question of whether it is nicer to allow the user to specify their decision via buttons in the quit dialog ("Save entry and quit", "Discard entry and quit", "Continue editing"), or require them to dismiss the "Close anyway" dialog, commit the edit, then re-attempt the quit.

It seems to me that it is a friendlier user experience to allow "Save entry and quit" from the quit dialog, while still providing the option for the user to back out of the quit if they realize that their edit is incomplete.  It is also in line with the way most other applications work when you attempt to quit while an edit is in progress, and so is the behavior a user would generally expect.

If the open entry has not actually been changed, there should be no need to display the quit dialog - this is a use-case I personally run into a lot:  I open an entry to examine the fields which are invisible in the overview (e.g. Notes), and then, without actually changing anything, want to quit the application, and encounter a pointless "Close anyway" dialog.

Finally, it might be a good idea to visually indicate which fields contain uncommitted changes (e.g. by bolding the label text or changing the field border or background color) so that it is more obvious what changes may or may not need to be committed or discarded before quitting.

**Comment by pakdel** [comment]
I added the save option.

**Comment by pakdel** [comment]
@debfx It looks like you have not been having enough time to review and merge pull requests. Could you give access to someone from the community?

**Comment by debfx** [comment]
> Yes, we could, but personally I prefer the current "decide on the task in hand before proceeding" approach.

You are absolutely right. We should keep these things separate.


> @debfx It looks like you have not been having enough time to review and merge pull requests. Could you give access to someone from the community?

It's really a lack of review bandwidth. Anyone can do that but I haven't seen anyone reviewing other's PRs.


I've merged the first commit.
The last one is not ready yet. It doesn't deal with the fact that EditEntryWidget::saveEntry() can go wrong.
Anyway this should be in another PR. Again sorry for mixing it into this one.

**Pull request closed without merging**
