### PR TITLE
KDBX 4 support

### PR DESCRIPTION
**Pull request by angelsl**
There are a few things that aren't done very well at the moment (format details leak into the GUI code, for example), but this is otherwise functionally complete.

Please review. I'll be continuing to change some things to deal with multiple ciphers more properly (to avoid hardcoding things everywhere), but this can merge first.

### CODE REVIEW

**Comment by angelsl** [comment]
I just realised Travis CI will fail.

Let me figure out how to get libgcrypt 1.7 and libargon2 onto Travis because it doesn't offer any recent Ubuntu version...

**Comment by phoerious** [comment]
Hey @angelsl 
I don't want to want to lure you away from KeePassX, but could you maybe submit this PR to KeePassXC, so we can review it there? https://github.com/keepassxreboot/keepassxc
We planned this feature for our 2.2.0 release.

**Comment by angelsl** [comment]
@phoerious,

Yeah, I was going to do that, give me a while :)

**Comment by phoerious** [comment]
Sure. :-)

**Pull request closed without merging**
