### PR TITLE
Bug #289

### PR DESCRIPTION
**Pull request by pakdel**
Auto-Type can be disabled altogether

### CODE REVIEW

**Comment by mdik** [comment]
wow. thank you!

**Comment by pakdel** [comment]
@aaron0x @Codifier Could you please review this Pull Request?

**Comment by pakdel** [comment]
@aaron0x thanks for the review :+1:

**Comment by jonathancross** [comment]
What ever happened to this?

**Comment by pakdel** [comment]
Apparently owners of the repository did not like any of my PullRequests. None of them got merged, so I simply stopped following up or developing new code for it.

**Comment by jonathancross** [comment]
@pakdel That is really sad to hear!
I'm new around here, but maybe @debfx can help figure out why your pull request is just collecting dust?

**Comment by pakdel** [comment]
I moved on to https://github.com/keepassxreboot/keepassxc

**Pull request closed without merging**
