### PR TITLE
Detect background changes to database file.

### PR DESCRIPTION
**Pull request by francoisferrand**
This gives the option to reload the database.
A setting is available to let the program automatically reload the
database if there is no change, always ignore, or always ask what to do.

### CODE REVIEW

**Comment by eternaltyro** [comment]
+1 Long time pending?

**Comment by Tklaversma** [comment]
Does anyone know the current status of this feature, also known as issue #73? Can't wait for it to be merged into KeePass..

**Comment by daniellandau** [comment]
I rebased unto current master (see https://github.com/daniellandau/keepassx/tree/autoreload) and it seems to still work. This is extremely useful for people who sync the database with other devices and never close their computer or KeePassX.

**Comment by Tklaversma** [comment]
So your saying you got a working example? If so, could you post the executable for Mac?

**Comment by daniellandau** [comment]
I don't regularly use a Mac (I use Linux), but I might be able to find one in a week or two. If anyone else can produce an executable (or you yourself, it's not terribly hard!) that's preferrable.

And yes, it does work for me.

**Comment by Tklaversma** [comment]
Since I do not have the knowledge, I would appreciate it very much if you or someone else can compile it for me (and a lot of others I guess...).

Thanks in advance!

**Comment by daniellandau** [comment]
I couldn't find a suitable Mac, but you should really go ahead and build it yourself. You can open an issue in my fork and I'll help you with the steps. Start with https://github.com/keepassx/keepassx#from-source

**Comment by phoerious** [comment]
This is implemented in the upcoming [KeePassXC](https://github.com/keepassxreboot/keepassxc) version 2.1.0.

**Pull request closed without merging**
