### PR TITLE
Qt5 support

### PR DESCRIPTION
**Pull request by mathstuf**
---
See #17 for the original submission. #70 is also asking for this.

### CODE REVIEW

**Comment by metasystem** [comment]
is qt5 fully supported now?

**Comment by mathstuf** [comment]
This branch built against it, but I may have missed something.

**Comment by m-kuhn** [comment]
It may be nice to use automoc instead of having all the conditional wrap_cpp directives in cmake.

**Comment by mathstuf** [comment]
Automoc done.

**Comment by mathstuf** [comment]
Automoc requires 2.8.6 as the minimum CMake version, but this only really rules out Debian oldstable (though available in backports) and RHEL5.

**Comment by metasystem** [comment]
Are y ou sur users from debian oldstable & rehl5 use keepassx or keepass? This config will ne more présent on full tty or ssh server nom? And are they use qt5?

**Comment by mathstuf** [comment]
Sorry, I was informing of where 2.8.6 is not available without compiling from source. The minimum version is bumped with Qt4 as well since it has automoc support too (and the idea was to remove conditionals). 2.8.6 was released in October 2011 or so.

**Comment by mathstuf** [comment]
Eh, seems the `$<TARGET_FILE:> thing isn't working right? I'll look into it tonight.

**Comment by mathstuf** [comment]
Updated the branch with the fix for testing. Should be good to go (I also verified that Qt4 still builds and tests as well) if you're fine with it.

**Comment by metasystem** [comment]
Still have some bug. We don't have global auto-type keyword set on qt5. So I have it on 2.0 alpha 6 qt4 version. Is it normal? I can't perform auto-type on funtoo current/i3-WM ...

**Comment by mathstuf** [comment]
Hmm. I've never tried the autotype stuff. I'll try poking it tonight.

**Comment by mathstuf** [comment]
I can't get auto-type to work at all on master or at any point back to where it was added for 2.x. It does work for 0.4.3 though.

**Comment by euroelessar** [comment]
Any progress there?

@debfx, may you have a look here? What concerns do you have about the patch, may be I'm able to improve it to have it merged?

**Comment by mathstuf** [comment]
I'm unfamiliar with autotype, but it looks like moving it to 2.x is what broke it based on my testing (but I'm also on XMonad without EMWH support, so who knows). If someone else can get it to work on master and not here, that'd be new info to me.

**Comment by debfx** [comment]
I have pushed experimental Qt 5 support to the qt5 branch.

**Comment by m-kuhn** [comment]
Qt 5 branch compiles and runs fine on Fedora 22

**Comment by xf-** [comment]
qt5 branch compiles and runs fine on arch 64bit

**Comment by ArchangeGabriel** [comment]
@debfx: Any ETA regarding the 2.1 release with QT5 onboard? This is the last QT4 package left on my system, it would be so cool to be able to definitively get ride of it. ;)

**Pull request closed without merging**
