### PR TITLE
update qt5 to 5.9.1

### PR DESCRIPTION
**Pull request by abhishekmendhekar**

### CODE REVIEW

**Comment by raedah** [comment]
check out KeePassXC https://keepassxc.org Seems that KeePassX is not maintained anymore

**Comment by jonathancross** [comment]
@abhishekmendhekar This project is no longer maintained (see #204)
It would be great if you contributed to KeepassXC instead and closed this PR so others see 204 at the top of the pull request list.  Thanks.

**Comment by debfx** [comment]
Fixed in 181ab27eb9f0bd2b6478f0c22684b742d44c4e2f

**Comment by rockihack** [comment]
@debfx Glad to see that you're fixing issues :+1: 
What is your opinion about those two bugs reported to keepassxc?

1) Transform seed is not re-generated on save (as it is in keepass):
https://github.com/rockihack/keepassx/commit/1b0e1c2dfba2adb579ddcf5e1afea66d4afdc56e

2) Fall-through in SymmetricCipherGcrypt::process error propagation:
https://github.com/rockihack/keepassx/commit/c9d8e537763f96e66bd2a5c4ce873bc596b95ad5

**Comment by debfx** [comment]
1. I don't see the point of doing that. The key is randomized anyway through MasterSeed.
   Actually it's probably counter productive as the delay when saving the database might causes users to reduce the master key rounds.

2. Yep that's a bug. Thanks for spotting. Applied as bbcacf489235e9e22687547e565c572f20e77ac4

**Comment by rockihack** [comment]
@debfx A static transform seed is at least an information leak, because it's part of the unencrypted header.
An attacker can deduce if the password was changed between two versions of a single database.
But I don't think it's a severe issue and I agree with you that a delay while saving the database is annoying.

**Pull request closed without merging**
