### PR TITLE
Add setting to match URL for auto-type

### PR DESCRIPTION
**Pull request by dakra**
I use a browser extension that puts the full URL in the window title and often the 'title' entry in keepass is not in the URL.
This patch adds an option to also compare the entry URL to the window title.
(keepass has the same option)

### CODE REVIEW

**Comment by nmschulte** [comment]
You're aware of the "Auto-Type" settings for the entry, yes?  With those settings, one can add any number of different window titles, each capable of defining their own auto-type sequence in addition to a unique sequence for the entry.  (I never use these settings, and they clutter and conflate the UI/UX, IMO, but that's a separate issue.)

Does KeePassX normally match the entry's "title" to the window titles for auto-typing?  I don't see that working too well for most users, as the "title" attribute is to identify the entry in the database, coming up with a system that works for both (entry identification _and_ auto-type matching) is probably an effort in frustration.

**Comment by dakra** [comment]
> You're aware of the "Auto-Type" settings for the entry, yes? 

I'm aware of them but I guess you only want to use them in some special cases.
I don't want to add the URL I already entered in another field to *every* entry again.

> Does KeePassX normally match the entry's "title" to the window titles for auto-typing? I don't see that working too well for most users, as the "title" attribute is to identify the entry in the database, coming up with a system that works for both (entry identification and auto-type matching) is probably an effort in frustration.

Have you tried it? It works like a charm.
Some people use the keepasshttp plugin but I find that using this plugin:
https://chrome.google.com/webstore/detail/url-in-title/ignpacbgnbnkaiooknalneoeladjnfgb (that just adds the full URL in the title) combined with the normal window auto-type to be more than sufficient.

Only problem was that keepassx (unlike keepass) doesn't have an option to match the window title with the database URL entry. Hence the pull request ;)

**Comment by dzhus** [comment]
@dakra How does the auto-type detect which field to put the password in when you use it for Chrome tabs like this?

**Comment by nmschulte** [comment]
> How does the auto-type detect which field to put the password in when you use it for Chrome tabs like this?

The same way it does when it's working otherwise: it doesn't detect any fields, it just starts sending keystrokes.

**Comment by dakra** [comment]
Like @nmschulte said, it doesn't.
I just click on the username field and then press the auto-type hotkey.
In some rare cases the default `user->tab->password->tab->enter`
is not correct and you have to define your custom sequence,
but that's not specific to this patch and a general auto-type thing.

**Comment by partik1** [comment]
I'd also prefer if instead of window's title, the auto-type was based on the URL. I suppose this is not yet implemented, or am I missing something?

**Comment by dzhus** [comment]
Why don't you just use chromeIPass?

**Comment by dakra** [comment]
Closing this as it's implemented in keepassxc.

**Pull request closed without merging**
