### PR TITLE
If password is visible, type in both fields at once

### PR DESCRIPTION
**Pull request by victorhaggqvist**
This resolves https://www.keepassx.org/dev/issues/200

### CODE REVIEW

**Comment by pakdel** [comment]
I prefer typing it twice, even if it is visible. I can easily mistake a __0__ with an __O__, or put in wrong number of spaces or swap in an __I__ for an __l__, and so on and so forth.

**Comment by alerque** [comment]
I'm going to have to say I prefer twice too. The only exception would be when copy pasting but in that case it's not much trouble to paste twice and consistent behavior (i.e. field focus and tab order being the same no matter what the options are) I think it might be better to leave this be.

**Comment by xf-** [comment]
I also prefer twice.
If you need to type it from a image or paper, it is better to have a validation.
This could be a setting and optional.

**Comment by victorhaggqvist** [comment]
@pakdel If that is a problem, we should really consider changing font in those fields to increase the visibility. Though I can't recall ATM how the visibility is currently, maybe one should check on that.

@xf- Yeah, if not default, a setting would be nice.

Would a setting be an accepted solution?

**Comment by dummer** [comment]
:+1:

**Comment by pakdel** [comment]
I think having it as an option would be good, but I am still thinking how many are going to use it?
 @cbrunet @jkt628 @GulBroz @eugenesan @psi-4ward @ezeeyahoo What do you think?

**Comment by jkt628** [comment]
i think type it twice avoids mistakes but an option satisfies everyone

**Comment by victorhaggqvist** [comment]
Just ignore me closing this ATM, rebased of master without thinking... was just about to commit a setting  implementation. Will unmess this in a minute.

**Comment by pakdel** [comment]
Can you make it an option that disables the second text box when the password is visible. I think it would be more intuitive.

**Comment by victorhaggqvist** [comment]
Github don't seem to pick up my commits here now. But current changes are at https://github.com/victorhaggqvist/keepassx/commits/password-autocopy.

@pakdel That I didn't even think of. But you are right, that would probably be a way better approach to it. I'll give it a go.

**Comment by victorhaggqvist** [comment]
Per @pakdel's suggestion passwords are now mirrored with disabled repeat field.

**Pull request closed without merging**
