### PR TITLE
Add support for browsers integration: a first step

### PR DESCRIPTION
**Pull request by shaform**
It appears that #110, #111 are not being merged due to multiple concerns:
- Too much unrelated commits to be cleaned up.
- Copyright concerns.
- Unit tests.
- Coding style.
- One class per file.

Therefore, this pull request attempts to resolve this issue by only introducing a very early implementation (Typz/keepassx@ea992bc), which has already been released under GPL  (Typz/keepassx#1). I also made some modifications (remove qjson & qhttpserver dependency and use libevent instead) to make it compatible with 2.0.

Once the change is merged, it would be easier to introduce further incremental changes to support full feature set. 

As the change is small, it could also be potentially easier for me to resolve coding style and unit test issues while continuously aligning the code with the current master branch.

So the only potential blocker may be the plugin architecture:

> debfx commented on Oct 16, 2015
> KeePassX needs to gain a proper plugin architecture. I plan to work on this once 2.0 is released.

But perhaps we could merge it first and refactor again when the plugin architecture comes. What do you think?
- [x] One class per file
- [x] Qt 5
- [x] Coding Style
- [x] Unit tests
  - [x] HttpServer
  - [x] Request
  - [x] Response
  - [x] Server
  - [x] Service

### CODE REVIEW

**Comment by fcore117** [comment]
Wonderful, thank you and i really hope this will be merged so i can quit KeePass and abandon firefox and can use chromium. I plan to nuke .net framework out of windows with winreducer and keepass is last obstacle.

**Comment by shaform** [comment]
@fcore117 
Thanks for the support. I am also a KeePass user looking to switch to KeePassX!

Now I've finally completed basic unit tests for each component. So this PR should now be ready for review.

**Comment by bradst** [comment]
Thanks for working on this! Hopefully this PR will have an easier time being merged. It's a shame that so many people can't switch to KeePassX because it lacks browser integration.

**Comment by rockihack** [comment]
A lot of people demand browser integration, but personally I do not want any kind of networking code in my password manager. We need a plugin system for this kind of features.

**Comment by fcore117** [comment]
plugins or not but as of now it is urgent need, rockihack: you could just disable it if you do not want and anyway it is local lan only.

**Comment by rockihack** [comment]
@fcore117 I know it listens on the loopback interface per default,
but I don't want any networking code in my password manager at all.
It intodruces new kinds of security issues (e.g. API to receive passwords)
and if the code is included it can be enabled an abused.

**Comment by mossholderm** [comment]
On Sep 22, 2016 3:05 AM, "jvoisin" <notifications@github.com> wrote:
>
> I agree with @rockihack. There has been a lot of vulnerabilities recently
with password-manager implementing browser integration.
>
> I also don't think that "it is urgent need" is a wise argument for
merging something ; I would really prefer to have this in a plugin that has
to be installed separately, instead of Keepassx core.

There are a lot of people who either want or don't want this, so a binary
decision is probably not the correct approach. Why not put it behind a
compile-time flag?

A plugin at a later date would be better, but there is no such
infrastructure today. We have the code, so why not implement it for those
who need it, but make it easily disabled?

**Comment by fcore117** [comment]
If google had integrated ultrastrong master password system then chromium could work without external password managers.

**Comment by shaform** [comment]
Closing this issues since we have https://github.com/keepassxreboot/keepassxc, which already supports browser integration, and it looks like this PR is unlikely to be merged.

**Comment by fcore117** [comment]
yep, using KeepassXC over 2 months now and works perfect like it should be with Chromium. Finally i have dropped that .net based keepass which was much slower.

**Pull request closed without merging**
